addSbtPlugin("org.typelevel"      % "sbt-typelevel"          % "0.8.5")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-site"     % "0.8.5")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-scalafix" % "0.8.5")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"            % "1.21.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"       % "0.5.11")
addSbtPlugin("com.github.xuwei-k" % "unused-code-plugin"     % "0.4.1")
